photo_sharing/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.home_feed, name='home'),
    path('post-like/<int:pk>/', views.post_like, name='post-like'),
    path('post-likes/<int:pk>/', views.likes_list, name='likes-list'),
    path('global-posts/', views.global_posts, name='global-posts'),
    path('dynamic-load/', views.dynamic_load, name='dynamic-load'),
    path('dynamic-image-load/', views.dynamic_image_load, name='dynamic-image-load'),
    path('get-post-details/<int:id>/', views.get_single_post, name='get-post-details'),
    path('new-post/', views.create_post, name='create-post'),
    path('update-post/<int:id>/', views.update_post, name='update-post'),
    path('delete-post/<int:id>/', views.delete_post, name='delete-post'),
    path('search/users/', views.get_users, name='get-users'),
    path('post-likes-list/', views.post_likes_list, name='post-likes-list')
]

social_media_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from users.views import CustomLoginView, CustomLogoutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('photo_sharing.urls')),
    path('user/', include('users.urls')),
    path('login/', CustomLoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', CustomLogoutView.as_view(template_name='users/logout.html'), name='logout'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('profile/<str:username>/', views.profile, name='profile'),
    path('update-profile/', views.update_profile, name='edit-profile'),
    path('list/', views.user_list, name='user-list'),
    path('follow/<int:pk>/', views.follow, name='follow'),
    path('unfollow/<int:pk>/', views.unfollow, name='unfollow'),
    path('followers/<str:username>/', views.followers, name='followers'),
    path('following/<str:username>/', views.following, name='following'),
    path('register/', views.register, name='register')
]

photo_sharing/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image


class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='post-images')
    description = models.TextField()
    date_created = models.DateTimeField(auto_now_add=True)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        image = Image.open(self.image.path)
        imageDimensions = (600, 600)
        image.thumbnail(imageDimensions)
        image.save(self.image.path)

    def __str__(self):
        return f'{self.user.username} Post'


class PostLike(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.user} - Post #{self.post.id}'

photo_sharing/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, CreateView
from .models import Post, PostLike
from django.http import HttpResponse, Http404
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
from users.models import Profile
from django.contrib.auth.models import User
import json
from datetime import datetime


@login_required
def home_feed(request):
    following_list = list(Profile.objects.filter(user=request.user).values("following").all())
    following_list = list(map(lambda item: item["following"], following_list))
    following_list.append(request.user.id)
    newest_posts = Post.objects.filter(user_id__in=following_list).all().order_by('-date_created')[:10]
    return render(request, 'photo_sharing/post_list.html', {
        "post_likes": list(PostLike.objects.filter(user=request.user).values_list('post_id', flat=True).all()),
        "newest_posts": newest_posts,
        "home": True
    })

@login_required
def post_like(request, pk):
    user = request.user
    post = Post.objects.get(id=pk)
    if PostLike.objects.filter(user=user, post=post).all():
        PostLike.objects.get(user=user, post=post).delete()
        return HttpResponse("Removed Like")
    else:
        PostLike.objects.create(user=user, post=post)
        return HttpResponse("Added Like")

@login_required
def likes_list(request, pk):
    results = PostLike.objects.filter(post_id=pk).all()
    return render(request, 'photo_sharing/likes_list.html', {
        'results': results
    })

@login_required
def global_posts(request):
    return render(request, 'photo_sharing/global.html', {
        "post_likes": list(PostLike.objects.filter(user=request.user).values_list('post_id', flat=True).all()),
        "all_posts": Post.objects.all().order_by('-date_created')[:9],
        "global": True
    })

@login_required
def dynamic_load(request):
    
    start = int(request.GET["start"])
    end = int(request.GET["end"])

    # Only gets posts of following & current users posts
    following_list = list(Profile.objects.filter(user=request.user).values("following").all())
    following_list = list(map(lambda item: item["following"], following_list))
    following_list.append(request.user.id)

    results = list(Post.objects.filter(user_id__in=following_list).all().values('id', 'user', 'image', 'description', 'date_created').order_by("-date_created"))
    
    posts = []
    
    current_user_post_likes = list(PostLike.objects.filter(user=request.user).all().values("post"))
    current_user_post_likes = [item["post"] for item in current_user_post_likes]

    for item in results[start:end]:
        post = item
        post["authorProfileImage"] = list(Profile.objects.filter(user_id=item['user']).all().values("image"))[0]["image"]
        post["author"] = list(User.objects.filter(id=item['user']).all().values("username"))[0]["username"]
        post["isLiked"] = True if item['id'] in current_user_post_likes else False
        post["postLikesCount"] = PostLike.objects.filter(post_id=item['id']).count()
        post["date_created"] = post["date_created"].strftime("%B %d, %Y")
        posts.append(post)

    if posts:
        return JsonResponse(posts, safe=False)
    else:
        return JsonResponse({"empty": True}, safe=False)

@login_required
def get_single_post(request, id):
    post = list(Post.objects.filter(id=id).all().values('id', 'user', 'image', 'description', 'date_created'))

    if post:
        post = post[0]
        current_user_post_likes = list(PostLike.objects.filter(user=request.user).all().values("post"))
        current_user_post_likes = [item["post"] for item in current_user_post_likes]
        post["authorProfileImage"] = list(Profile.objects.filter(user_id=post['user']).all().values("image"))[0]["image"]
        post["author"] = list(User.objects.filter(id=post['user']).all().values("username"))[0]["username"]
        post["isLiked"] = True if post['id'] in current_user_post_likes else False
        post["postLikesCount"] = PostLike.objects.filter(post_id=post['id']).count()
        post["date_created"] = post["date_created"].strftime("%B %d, %Y")
        return JsonResponse(post, safe=False)
    else:
        raise Http404("Post could not be found.")

@login_required
def dynamic_image_load(request):
    start = int(request.GET["start"])
    end = int(request.GET["end"])

    posts = list(Post.objects.all().values('id', 'image').order_by("-date_created"))

    posts = posts[start:end]

    if posts:
        return JsonResponse(posts, safe=False)
    else:
        return JsonResponse({"empty": True}, safe=False)

@login_required
def create_post(request):
    if request.method == "POST":
        image = request.FILES.get('image')
        description = request.POST.get('description')
        image_type = image.__dict__["content_type"]
        if not image or not description:
            # Add in messages.error message here
            return redirect('/new-post/')
        if image_type != "image/jpeg" and image_type != "image/png":
            # Add in messages.error message here
            return redirect('/new-post/')
        for letter in "<>":
            if letter in description:
                # Add in error message here
                return redirect('/new-post/')
        Post.objects.create(user=request.user, image=image, description=description)
        return redirect(f'/user/profile/{request.user.username}/')
    return render(request, "photo_sharing/create_post.html", {"createPost": True})

@login_required
def update_post(request, id):
    if request.method == "POST":
        post = Post.objects.get(id=id)
        if not(post):
            raise Http404
        data = json.loads(request.body)
        description = data['description']
        for letter in "<>":
            if letter in description:
                raise Http404()
        if post.user == request.user:
            post.description = description
            post.save()
            return HttpResponse("post updated")
    raise Http404()

@login_required
def delete_post(request, id):
    if request.method == "POST":
        post = Post.objects.get(id=id)
        if not(post):
            raise Http404()
        if post.user == request.user:
            post.delete()
            return HttpResponse("post deleted")
    raise Http404()

@login_required
def get_users(request):
    query = request.GET.get("search")
    users = list(User.objects.filter(username__contains=query).all().values('username', 'id'))
    if len(users) > 5:
        users = users[:4]
    for user in users:
        user["profileImage"] = list(Profile.objects.filter(user_id=user['id']).all().values('image'))[0]['image']
    return JsonResponse(users, safe=False)

@login_required
def post_likes_list(request):
    post_likes = list(PostLike.objects.filter(user=request.user).values('post_id').all())
    post_likes = list(map(lambda item: item['post_id'], post_likes))
    posts = Post.objects.filter(id__in=post_likes).all().order_by('-date_created')
    return render(request, "photo_sharing/post_likes_list.html", {
        "posts": posts,
        "post_likes": list(PostLike.objects.filter(user=request.user).values_list('post_id', flat=True).all())
    })

photo_sharing/templates/photo_sharing/create_post.html
{% extends 'photo_sharing/layout.html' %}
{% block content %}
{% load static %}
<br><br>
<div class='create-post-background'>
  <h2 class='create-post-title'>Create New Post</h2>
  <form action="{% url 'create-post' %}" method="POST" enctype="multipart/form-data" class='create-post-form'>
    {% csrf_token %}
    <div class='upload-image-div'>
      <label for="image-upload" class='uploaded-image'>
        <img src="" alt="Uploaded Image" id='uploadedImage'>
        <div class='upload-image-text'>
          <span><i class="fa fa-upload" aria-hidden="true"></i></span>
          <span class='upload-text'>Upload Image</span>
        </div>
      </label>
      <label for="image-upload" class='upload-post-btn'>Upload Post Image</label>
      <input type="file" name="image" class='image-upload' id='image-upload'>
    </div>
    <div class='description-div'>
      <label for="create-post-description" class='post-description-label'>Enter Post Description:</label>
      <textarea type="text" name="description" class='create-post-description' id='create-post-description'></textarea>
      <div class='spacer'></div>
      <button type="submit" class='create-post-btn'>Create Post</button>
    </div>
  </form>
</div>
<script src='{% static "photo_sharing/form.js" %}'></script>
{% endblock %}

photo_sharing/templates/photo_sharing/global.html
{% extends "photo_sharing/layout.html" %}

{% block content %}
{% load static %}

<div class='global-background'>
<div class='dark-background'>
    <div class='global-feed'>
        {% for post in all_posts %}
            <div class='post-img-div'>
                <img data-id='{{post.id}}' class='post-img' src="{{ post.image.url }}" alt="Post Image">
            </div>
        {% endfor %}
    </div>
</div>
<div class='custom_modal'>
    <div class='custom_modal__exit-btn'><i class="fa fa-times" aria-hidden="true"></i></div>
    <div class='custom_modal__container'>
        <button class='next-btn'><i class="fa fa-chevron-right" aria-hidden="true"></i></button>
        <button class='previous-btn'><i class="fa fa-chevron-left" aria-hidden="true"></i></button>
    </div>
</div>
</div>
<script src="{% static 'photo_sharing/modal.js' %}"></script>

{% endblock %}

photo_sharing/templates/photo_sharing/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Photo Sharing App</title>
    <link rel="icon" href="https://www.atwellcreative.ca/wp-content/uploads/2017/04/cropped-atwell-favicon-1.png" type="image/gif" sizes="16x16">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Lobster&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'photo_sharing/main.css' %}">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light">
      <a href='/' {% if not user.is_authenticated %} class='login-title' {% endif %}><h1>Photo App</h1></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      {% if user.is_authenticated %}
      <div class='nav-search'>
        <form class="form-inline my-2 my-lg-0" action='/user/list/'>
            <input class="form-control mr-sm-2 search-input" type="text" name='q' placeholder="Search..." aria-label="Search" autocomplete="off">
            <button class="my-2 my-sm-0 search-btn" type="submit"><i class="fa fa-search" aria-hidden="true"></i></button>
            <div class='loading-icon'>
                <div class="lds-spinner"><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div></div>
            </div>
        </form>
        <div class='search-results'>
        </div>
      </div>
      {% endif %}

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
                <li class='nav-item mx-auto'><a class='nav-link {% if home %} active {% endif %}' data-toggle="tooltip" data-placement="bottom" title="Home" href='{% url "home" %}'><span class='desktop-nav-icon'><i class="fa fa-home" aria-hidden="true"></i></span><span class='mobile-nav-title'>Home</span></a></li>
                <li class='nav-item mx-auto'><a class='nav-link {% if global %} active {% endif %}' data-toggle="tooltip" data-placement="bottom" title="Global Feed" href='{% url "global-posts" %}'><span class='desktop-nav-icon'><i class="fa fa-globe" aria-hidden="true"></i></span><span class='mobile-nav-title'>Global Feed</span></a></li>
                <li class='nav-item mx-auto'><a class='nav-link {% if profile %} active {% endif %}' data-toggle="tooltip" data-placement="bottom" title="Profile" href='{% url "profile" user.username %}'><span class='desktop-nav-icon'><i class="fa fa-user" aria-hidden="true"></i></span><span class='mobile-nav-title'>Profile</span></a></li>
                <li class='nav-item mx-auto d-none search-nav-title {% if search %} active {% endif %}'><a class='nav-link' data-toggle="tooltip" data-placement="bottom" title="Create Post" href='/user/list/?q='><span class='mobile-nav-title'>Search</span></a></li>
                <li class='nav-item mx-auto'><a class='nav-link {% if createPost %} active {% endif %}' data-toggle="tooltip" data-placement="bottom" title="Create Post" href='{% url "create-post" %}'><span class='desktop-nav-icon'><i class="fa fa-plus-square" aria-hidden="true"></i></span><span class='mobile-nav-title'>Create Post</span></a></li>
                <li class='nav-item mx-auto'><a class='nav-link {% if logout %} active {% endif %}' data-toggle="tooltip" data-placement="bottom" title="Logout" href='{% url "logout" %}'><span class='desktop-nav-icon'><i class="fa fa-sign-out" aria-hidden="true"></i></span><span class='mobile-nav-title'>Logout</span></a></li>
            {% else %}
                <li class='nav-item mx-auto'><a class='nav-link logged-out-link {% if login %} active {% endif %}' href='{% url "login" %}'>Login</a></li>
                <li class='nav-item mx-auto'><a class='nav-link logged-out-link {% if register %} active {% endif %}' href='{% url "register" %}'>Register</a></li>
            {% endif %}
        </ul>
      </div>
    </nav>
    {% if messages %}
        {% for message in messages %}
            {% if message.tags == 'error' %}
                <div class='alert alert-danger text-center alert-dismissible fade show mb-0' role="alert">
                    {{ message }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            {% else %}
                <div class='alert alert-{{ message.tags }} text-center alert-dismissible fade show mb-0' role="alert">
                    {{ message }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            {% endif %}
        {% endfor %}
    {% endif %}
    <main>
    {% block content %} {% endblock %}
    </main>
    <!-- <footer>
        <a><h3>logo name</h3></a>
    </footer> -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    <script src='{% static "photo_sharing/search.js" %}'></script>
</body>
</html>

photo_sharing/templates/photo_sharing/likes_list.html
{% extends 'photo_sharing/layout.html' %}

{% block content %}
<br>
<div class='text-center'>
    <h3 class="page-title">Post Likes</h3>
</div>
{% for like in results %}
<div class="row no-gutters user-page">
    <div class='col-12 profile-background my-2'>
        <div class="profile-block">
            <div class='image-col mr-3 pl-1 my-auto'>
                <img class='profile-image' src="{{ like.user.profile.image.url }}" alt="User Profile Image">
            </div>
            <div class='bio-col my-auto pr-0'>
                <a class='username-link' href="{% url 'profile' like.user.username %}"><h4>{{ like.user.username|title }}</h4></a>
                <p class='mb-2'>{{ like.user.profile.bio|truncatechars:90 }}</p>
                {% if like.user.username == user.username %}
                <div class='py-2'></div>
                {% elif like.user not in following_list %}
                <a class='btn user-btn follow' data-id='{{ like.user.id }}' href="{% url 'follow' like.user.id %}">Follow <i class="fa fa-user" aria-hidden="true"></i></a>
                {% else %}
                <a class='btn user-btn unfollow' data-id='{{ like.user.id }}' href="{% url 'unfollow' like.user.id %}">Unfollow <i class="fa fa-user" aria-hidden="true"></i></a>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% empty %}
<div class="row no-gutters user-page">
    <div class='col-12 profile-background my-3'>
        <div class="profile-block">
            <p class='m-auto p-4'>This post does not have any likes.</p>
        </div>
    </div>
</div>
{% endfor %}
{% endblock %}

photo_sharing/templates/photo_sharing/post_likes_list.html
{% extends 'photo_sharing/layout.html' %}
{% block content %}
{% load static %}
<div class='custom_row'>
<div class='first-col'>
</div>
<div class='center-col'>
    <div id='liked-posts-list'>
        <br>
        <div class='text-center'>
            <div class="page-title home-title">
                Your Post Likes
            </div>
        </div>
        {% for post in posts %}
            <div class="row no-gutters justify-content-center home">
                <div class="col-12 post-block">
                    <div class='post-image'>
                        <img src="{{ post.image.url }}" alt="Post Image">
                    </div>
                    <div class='post-description-section'>
                        <div class='post-user-image'>
                            <img src="{{ post.user.profile.image.url }}" alt="User Profile Image">
                        </div>
                        <div class='post-description'>
                            <a class='username-link' href="{% url 'profile' post.user.username %}"><h6>{{ post.user.username|title }}</h6></a>
                                <div class='likes'><a href="{% url 'likes-list' post.id %}"><p>
                                    {% if post.postlike_set.all.count > 0 %}
                                    <span class="likes-count">{{ post.postlike_set.all.count }}</span>
                                    {% else %}
                                    <span class="likes-count likes-hidden">0</span>
                                    {% endif %}
                                    {% if post.postlike_set.all.count == 1 %}
                                    <span id="like-title"> Like</span>
                                    {% elif post.postlike_set.all.count > 1 %}
                                    <span id="like-title"> Likes</span>
                                    {% else %}
                                    <span class='likes-hidden' id="like-title"> Like</span>
                                    {% endif %}
                                    </p></a></div>
                            <p class='post-p'><span class='post-text' data-description='{{ post.description|capfirst }}'>{{ post.description|capfirst|truncatechars:90 }}</span> {% if post.description|length > 90 %} <button class='post-read-more-btn'>Read More</button> {% endif %} </p>
                            {% if post.id not in post_likes %}
                            <a href="{% url 'post-like' post.id %}" data-id="{{post.id}}" class='like-btn'><p><i class="fa fa-heart" aria-hidden="true"></i>Like Post</p></a>
                            {% else %}
                            <a href="{% url 'post-like' post.id %}" data-id="{{post.id}}" class='like-btn liked'><p><i class="fa fa-heart" aria-hidden="true"></i>Liked Post</p></a>
                            {% endif %}
                            <p class='post-date'>{{ post.date_created|date:'F d, Y' }}</p>
                        </div>
                    </div>
                </div>
            </div>
        {% empty %}
        <div class='bg-dark text-white py-3 px-4 mt-4'>Your feed is empty. Begin following people to see their posts here.</div>
        {% endfor %}
    </div>
</div>
<div class='last-col'>
</div>
</div>
<script src='{% static "photo_sharing/dynamicLoad.js" %}'></script>
{% endblock %}

photo_sharing/templates/photo_sharing/post_list.html
{% extends 'photo_sharing/layout.html' %}
{% block content %}
{% load static %}
<div class='custom_row'>
<div class='first-col'>
</div>
<div class='center-col'>
    <div id='global-posts'>
        <br>
        <div class='text-center'>
            <div class="page-title home-title">
                Home Feed
            </div>
        </div>
        {% for post in newest_posts %}
            <div class="row no-gutters justify-content-center home">
                <div class="col-12 post-block">
                    <div class='post-image'>
                        <img src="{{ post.image.url }}" alt="Post Image">
                    </div>
                    <div class='post-description-section'>
                        <div class='post-user-image'>
                            <img src="{{ post.user.profile.image.url }}" alt="User Profile Image">
                        </div>
                        <div class='post-description'>
                            <a class='username-link' href="{% url 'profile' post.user.username %}"><h6>{{ post.user.username|title }}</h6></a>
                                <div class='likes'><a href="{% url 'likes-list' post.id %}"><p>
                                    {% if post.postlike_set.all.count > 0 %}
                                    <span class="likes-count">{{ post.postlike_set.all.count }}</span>
                                    {% else %}
                                    <span class="likes-count likes-hidden">0</span>
                                    {% endif %}
                                    {% if post.postlike_set.all.count == 1 %}
                                    <span id="like-title"> Like</span>
                                    {% elif post.postlike_set.all.count > 1 %}
                                    <span id="like-title"> Likes</span>
                                    {% else %}
                                    <span class='likes-hidden' id="like-title"> Like</span>
                                    {% endif %}
                                    </p></a></div>
                            <p class='post-p'><span class='post-text' data-description='{{ post.description|capfirst }}'>{{ post.description|capfirst|truncatechars:90 }}</span> {% if post.description|length > 90 %} <button class='post-read-more-btn'>Read More</button> {% endif %} </p>
                            {% if post.id not in post_likes %}
                            <a href="{% url 'post-like' post.id %}" data-id="{{post.id}}" class='like-btn'><p><i class="fa fa-heart" aria-hidden="true"></i>Like Post</p></a>
                            {% else %}
                            <a href="{% url 'post-like' post.id %}" data-id="{{post.id}}" class='like-btn liked'><p><i class="fa fa-heart" aria-hidden="true"></i>Liked Post</p></a>
                            {% endif %}
                            <p class='post-date'>{{ post.date_created|date:'F d, Y' }}</p>
                        </div>
                    </div>
                </div>
            </div>
        {% empty %}
        <div class='home-sidebar'>
            <div class='sidebar-container'>
                <h3 class='sidebar-username'>Welcome, {{ user.username|title }}!</h3>
                <p class='sidebar-text'>You are not currently following any users.<br> You can follow users & their posts will appear here.</p>
                <div class='sidebar-btn-group'>
                <a href='/user/list/?q=' type="button" class="btn btn-light border sidebar-btn">View All Users</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
<div class='last-col'>
    
</div>
</div>
<script src='{% static "photo_sharing/dynamicLoad.js" %}'></script>
{% endblock %}